# Métodode Conjunto Activo

El problema es minimizar $$\frac{1}{2}(x_1^2 + x_2^2 + x_3^2) - x_3$$
sujeto a
$$\begin{align*}

\end{align*}$$

In [2]:
import numpy as np

In [3]:
Q = np.identity(3)
A = np.array([1., 1., 1.])
c = np.array([0., 0., -1.])
b = 1.
F = np.identity(3)
d = np.zeros(3)

## Caso 1

Iniciamos en el punto $\hat{x} = \begin{pmatrix}
1 \\
0 \\
0
\end{pmatrix}$, en donde el conjunto activo es $\mathcal{A}(\hat{x}) = \{2,3\}$. Escogemos el conjunto de trabajo $\mathcal{I} = \{2\}$.

In [4]:
# Caso 1
x_hat = np.array([1., 0., 0.])
c_hat = np.dot(Q, x_hat) + c
yy = np.array([0., 1., 0.])

A_hat = np.array([[1., 1., 1.],yy])
b_hat = np.zeros(2)

In [25]:
# Solución del subproblema
K = np.concatenate((Q, A_hat.T),1)
T = np.zeros((2,2))
M = np.concatenate((A_hat, T), 1)
K = np.concatenate((K,M)) # Matriz
ld = np.concatenate((-c_hat, np.array([0., 0.]))) # Lado Der

In [26]:
w = np.linalg.solve(K, ld)
p_star = w[:3]

In [27]:
p_star

array([-5.00000000e-01,  5.00000000e-01,  1.66533454e-16])

## Caso 2

Iniciamos en el punto $\hat{x} = \begin{pmatrix}
1 \\
0 \\
0
\end{pmatrix}$, en donde el conjunto activo es $\mathcal{A}(\hat{x}) = \{2,3\}$. Escogemos el conjunto de trabajo $\mathcal{I} = \{3\}$.

In [56]:
# Caso 2
x_hat = np.array([1., 0., 0.])
c_hat = np.dot(Q, x_hat) + c
yy = np.array([0., 0., 1.])

A_hat = np.array([[1., 1., 1.],yy])
b_hat = np.zeros(2)

In [63]:
# Solución del subproblema
K = np.concatenate((Q, A_hat.T),1)
T = np.zeros((2,2))
M = np.concatenate((A_hat, T), 1)
K = np.concatenate((K,M)) # Matriz
ld = np.concatenate((-c_hat, np.array([0., 0.]))) # Lado Der

w = np.linalg.solve(K, ld)
p_star = w[:3]
p_star

array([ 1.23259516e-32, -1.00000000e+00,  1.00000000e+00])

In [64]:
# Nuevo punto
x_hat += 2*p_star # Ojo: el coeficiente es para escalar el vector p
x_hat

array([1.23259516e-32, 1.11022302e-16, 1.00000000e+00])

In [62]:
c_hat = np.dot(Q, x_hat) + c
yy = np.array([1., 0., 0.])

A_hat = np.array([[1., 1., 1.],yy])

In [65]:
# Otra solución del subproblema
K = np.concatenate((Q, A_hat.T),1)
T = np.zeros((2,2))
M = np.concatenate((A_hat, T), 1)
K = np.concatenate((K,M)) # Matriz
ld = np.concatenate((-c_hat, np.array([0., 0.]))) # Lado Der

w = np.linalg.solve(K, ld)
p_star = w[:3]
p_star

array([ 1.23259516e-32, -1.00000000e+00,  1.00000000e+00])

In [66]:
x_hat += p_star
x_hat

array([ 2.46519033e-32, -1.00000000e+00,  2.00000000e+00])

## Caso 3

In [67]:
# Caso 3
x_hat = np.array([0., 0., 1.])
c_hat = np.dot(Q, x_hat) + c
yy = np.array([1., 1., 0.])

A_hat = np.array([[1., 1., 1.],yy])
b_hat = np.zeros(2)

# Solución del subproblema
K = np.concatenate((Q, A_hat.T),1)
T = np.zeros((2,2))
M = np.concatenate((A_hat, T), 1)
K = np.concatenate((K,M)) # Matriz
ld = np.concatenate((-c_hat, np.array([0., 0.]))) # Lado Der

w = np.linalg.solve(K, ld)
p_star = w[:3]
p_star

array([0., 0., 0.])

## Caso 4

In [77]:
# Caso 4
x_hat = np.array([0.5, 0.5, 0.])
c_hat = np.dot(Q, x_hat) + c
yy = np.array([]) # escogemos el vacío

A_hat = np.array([1., 1., 1.])
b_hat = np.zeros(1)

# Solución del subproblema
K = np.concatenate((Q, A_hat.T),0)
T = np.array[0.]
M = np.concatenate((A_hat, T), 1)
K = np.concatenate((K,M)) # Matriz
ld = np.concatenate((-c_hat, np.array([0.]))) # Lado Der

w = np.linalg.solve(K, ld)
p_star = w[:3]
p_star

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [71]:
Q

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
A_hat.T

array([1., 1., 1.])

In [81]:
#TODO
# Falta hacer la función qp_directo(Q,A,c,b) para programación cuadrática convexa. Estará en canvas o en la foto del 21/02/2024 19:51