# Laboratorio 2

In [21]:
import numpy as np
from matplotlib import pyplot

In [28]:
m = 5
n = 9
A = np.random.rand(m,n)
b = np.random.randn(m)
c = np.ones(n)
r = np.linalg.matrix_rank(A)
print(f"Rango de A: {r}")
Q = np.random.rand(n, n)

# Encontrar la factorización QR
V, R = np.linalg.qr(Q)

# Generamos una matriz simétrica positiva def.
Q = np.dot(R.T, R)

Rango de A: 5


## Descomposición en Valores Singulares

In [23]:
(U, S, Vh) = np.linalg.svd(A, full_matrices=True)

V = Vh.T
Z = V[:,m:n]
(m1, n1) = Z.shape

print(f"Dimensiones de Z: {m1}x{n1}")

Dimensiones de Z: 9x4


In [24]:
matriz_ceros = np.dot(A,Z)
print(f"Checamos el espacio nulo:\n{matriz_ceros}")

Checamos el espacio nulo:
[[ 8.12032626e-19 -7.73980917e-17 -5.33822881e-16 -2.19197578e-16]
 [ 2.06837691e-18 -3.83006633e-17 -3.84465549e-16 -1.52888509e-16]
 [-6.96078376e-17  3.18586851e-17 -2.23674746e-16 -9.73157573e-17]
 [-1.02328766e-16 -3.40111319e-17 -2.87472936e-16 -1.71593614e-16]
 [ 1.66533454e-16 -2.77555756e-17 -5.55111512e-17 -1.11022302e-16]]


## Solución particular de $Ax = b$ con SVD

In [25]:
UT = U.T
S_inv = np.diag(1/S)
S_star = np.concatenate((S_inv, np.zeros((n-m,m))))
A_star = np.dot(np.dot(V, S_star), UT)
# Lo siguiente es una mejor manera de hacer: 
# >>> x_p = np.dot(A_star, b)
x_p = np.dot(UT, b)
x_p = np.dot(S_star, x_p)
x_p = np.dot(V, x_p)

Es mejor hacerlo por partes porque es computacionalmente más eficiente multiplicar por un vector que por una matriz. Entonces nos basamos en la propiedad de que 
$$ A^{*} b = (V \cdot S^{*} \cdot U^T) b$$

In [26]:
# Verificar que A*xp = b
np.dot(A, x_p) - b

array([6.38378239e-16, 2.22044605e-16, 8.88178420e-16, 4.99600361e-16,
       0.00000000e+00])

## Solución al problema cuadrático

In [ ]:
# TODO